### ISSUE TITLE
How to show Loader with delay of 3 seconds?

### ISSUE THREAD

**Issue by diliptiwari333** [sathishvgs/FullMaterialLoader#13]
I successfully implemented it on my live project which is working fine but i want somewhere to load for 3 seconds how will i do that i m using swift 3

**Comment by sathishvgs** [comment]
@diliptiwari333 Thanks for using FullMaterialLoader. We don't have this feature right now, you can implement on your own. 
 **startAnimating** -> Starts the loader animation to load. 
 **stopAnimating** -> Stops the loader animation

 By using the DispatchQueue.main you can implement the delay.
We will try to give this feature ASAP. Feel free to ask your questions.

**Comment by diliptiwari333** [comment]
yes pls implement asap loading based on seconds so it will be better and thanks for replying i was waiting for ur reply,its better because we can change loader color of any type @sathishvgs

**Comment by sathishvgs** [comment]
@diliptiwari333 Can you give your requirement in brief. The loader should animate for 3 seconds and it should hide right ?

**Comment by diliptiwari333** [comment]
yes @sathishvgs

**Comment by diliptiwari333** [comment]
thanks i will check @sathishvgs

**Comment by diliptiwari333** [comment]
i tried and it worked thanks @sathishvgs
