### ISSUE TITLE
Unable to build with Swift 4.2

### ISSUE THREAD

**Issue by ankitgoyalapplify** [sathishvgs/FullMaterialLoader#14]
Hello,

Following error is occurring with Xcode 10 and Swift 4.2: /Pods/FullMaterialLoader/FullMaterialLoader/Classes/MaterialLoader.swift:39:44: Type 'CAShapeLayerLineCap' (aka 'NSString') has no member 'round'

**Comment by sathishvgs** [comment]
@ankitgoyalapplify 
Thanks. Will check and update you soon.

**Comment by sathishvgs** [comment]
@ankitgoyalapplify 
We have updated the library to support swift 4.2. Can you check and let us know.

**Comment by AnmolMalpani** [comment]
Hello, 
I am still getting this issue. Please check it again.

**Comment by sathishvgs** [comment]
@AnmolMalpani ,
0.2.3 has updated for swift 4.2. It's working fine. Can you please check and confirm the swift version in build settings. BuildSettings -> swift_version

**Comment by AnmolMalpani** [comment]
@sathishvgs I am using less version compare to 4.2.

**Comment by AnmolMalpani** [comment]
@sathishvgs I am using less version compare to 4.2. So i wanna ask you which version is suitable for 4.0?

**Comment by ghost** [comment]
Hello @sathishvgs 

Now the code works perfectly with XCode 10 and Swift 4.2. Thank you for the prompt response.

Good Luck

**Comment by sathishvgs** [comment]
Hi @AnmolMalpani ,
I have updated the ReadMe File. Can you check and confirm it.
For Swift 4 and above use - 0.2.3
For lesser than Swift 4 use - 0.2.2

**Comment by AnmolMalpani** [comment]
@sathishvgs Now working fine. Thanks for support.
Good Luck.

**Comment by sathishvgs** [comment]
Thanks @AnmolMalpani
